// AWS Resource Configuration
// *** AUTO-GENERATED by deploy.sh from CloudFormation stack outputs ***
// Do not edit manually — run ./deploy.sh frontend to regenerate
const awsConfig = {
  region: '',
  userPoolId: '',
  userPoolClientId: '',
  websocketUrl: '',
};

export default awsConfig;
